# Generated by Django 6.0.6 on 2026-06-05 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default=None, help_text='Kenyan phone number', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone must be Kenyan format: 0712345678 or +254712345678', regex='^(\\+254|0)[17]\\d{8}$')]),
        ),
    ]
