# Generated by Django 6.0.6 on 2026-06-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('cashier', 'Cashier'), ('storekeeper', 'Storekeeper'), ('inventory_clerk', 'Inventory Clerk'), ('viewer', 'Viewer')], default='cashier', help_text="User's role determines permissions", max_length=20),
        ),
    ]
