# Generated by Django 6.0.6 on 2026-06-05 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, help_text='Primary email address', max_length=254, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='LoyaltyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_record_entries', to='customers.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='loyalty_points',
        ),
    ]
