# Generated by Django 6.0.6 on 2026-06-05 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_email_loyaltyrecord_and_more'),
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='payments_cu_phone_a0ea97_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='payments_cu_email_d87474_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='payments_cu_account_5444f5_idx',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='mpesa_result_code',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='mpesa_result_desc',
        ),
        migrations.AddField(
            model_name='mpesaaccount',
            name='payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_accounts', to='payments.paymentaccount'),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='maximum_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='minimum_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='mpesa_shortcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
